### PR TITLE
Added commentstring

### PR DESCRIPTION
**Pull request by subnut**

### CODE REVIEW

**Comment by rid9** [comment]
Can you please provide some details about this proposal? What's the reason for it and what are you planning to achieve with it?

**Comment by subnut** [comment]
Right. Sorry for not having mentioned it in the first post itself....

From the docs -
```vimhelp
					*'commentstring'* *'cms'* *E537*
'commentstring' 'cms'	string	(default "/*%s*/")
			local to buffer
	A template for a comment.  The "%s" in the value is replaced with the
	comment text.  Currently only used to add markers for folding, see
	|fold-marker|.
```

It is also used by [tpope/vim-commentary](https://github.com/tpope/vim-commentary) and other similar plugins to comment/uncomment lines easily.

**Comment by rid9** [comment]
The reason I'm concerned is that `commentstring` is never set in any of the syntax files included with vim. In fact, `set` is rarely used for anything other than setting and restoring `cpoptions`, so I'm not convinced this is the way things are done regarding comments.

**Comment by subnut** [comment]
You are right. I forgot that options are a part of _ftplugin_ files, not _syntax_ files...
Correctly implemented in the latest commit.

**Comment by rid9** [comment]
Looks good, thanks!

**Pull request merged**
